package com.datu.patient;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CollectionItem implements java.io.Serializable {

  static final long serialVersionUID = 1L;

  private int itemId;

  public CollectionItem() {
  }

  public int getItemId() {
    return this.itemId;
  }

  public void setItemId(int itemId) {
    this.itemId = itemId;
  }

  public CollectionItem(int itemId) {
    this.itemId = itemId;
  }
}